sonar.projectKey=csdt-eci_HospitalManagementRefactor
sonar.organization=csdt-eci

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Hospital Management Refactor
sonar.projectVersion=0.0.1-SNAPSHOT

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src/main/java,src/main/webapp
sonar.tests=src/test/java

# Test coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Java compilation
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

